services:
  php:
    build:
      context: .docker/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: reviews_php
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: dev
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.25-alpine
    container_name: reviews_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.3
    container_name: reviews_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviews
      MYSQL_USER: reviews
      MYSQL_PASSWORD: reviews
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: reviews_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      # point phpMyAdmin at your MySQL container
      PMA_HOST: db
      PMA_PORT: 3306
      # optional: pre-fill login form (you can still choose "root"/"root" or "reviews"/"reviews")
      PMA_USER: reviews
      PMA_PASSWORD: reviews
      # allow connecting to arbitrary servers if you want
      PMA_ARBITRARY: 1

volumes:
  db_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
